package accounting.ce.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import accounting.ce.Apcheck;
import accounting.ce.Apvoucherdist;
import accounting.ce.Vendor;

/**
 * Class _Apvoucher was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Apvoucher extends CayenneDataObject {

    public static final String AMOUNT_PROPERTY = "amount";
    public static final String DES_PROPERTY = "des";
    public static final String DISCTAKEN_PROPERTY = "disctaken";
    public static final String INVDATE_PROPERTY = "invdate";
    public static final String INVNUM_PROPERTY = "invnum";
    public static final String MEMO_PROPERTY = "memo";
    public static final String PONUM_PROPERTY = "ponum";
    public static final String PTD_PROPERTY = "ptd";
    public static final String RETHELD_PROPERTY = "retheld";
    public static final String VENNAME_PROPERTY = "venname";
    public static final String VENNUM_PROPERTY = "vennum";
    public static final String VOUCHERNUM_PROPERTY = "vouchernum";
    public static final String CHECKS_PROPERTY = "checks";
    public static final String DISTRIBUTION_PROPERTY = "distribution";
    public static final String VENDOR_PROPERTY = "vendor";

    public static final String VOUCHERNUM_PK_COLUMN = "vouchernum";

    public Double getAmount() {
        return (Double)readProperty("amount");
    }

    public String getDes() {
        return (String)readProperty("des");
    }

    public Double getDisctaken() {
        return (Double)readProperty("disctaken");
    }

    public Date getInvdate() {
        return (Date)readProperty("invdate");
    }

    public String getInvnum() {
        return (String)readProperty("invnum");
    }

    public String getMemo() {
        return (String)readProperty("memo");
    }

    public String getPonum() {
        return (String)readProperty("ponum");
    }

    public Double getPtd() {
        return (Double)readProperty("ptd");
    }

    public Double getRetheld() {
        return (Double)readProperty("retheld");
    }

    public String getVenname() {
        return (String)readProperty("venname");
    }

    public String getVennum() {
        return (String)readProperty("vennum");
    }

    public Integer getVouchernum() {
        return (Integer)readProperty("vouchernum");
    }

    public void addToChecks(Apcheck obj) {
        addToManyTarget("checks", obj, true);
    }
    public void removeFromChecks(Apcheck obj) {
        removeToManyTarget("checks", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Apcheck> getChecks() {
        return (List<Apcheck>)readProperty("checks");
    }


    public void addToDistribution(Apvoucherdist obj) {
        addToManyTarget("distribution", obj, true);
    }
    public void removeFromDistribution(Apvoucherdist obj) {
        removeToManyTarget("distribution", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Apvoucherdist> getDistribution() {
        return (List<Apvoucherdist>)readProperty("distribution");
    }



    public Vendor getVendor() {
        return (Vendor)readProperty("vendor");
    }


}
