package accounting.ce.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Glinfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Glinfo extends CayenneDataObject {

    public static final String GLPERIOD_PROPERTY = "glperiod";
    public static final String STARTMONTH_PROPERTY = "startmonth";

    public static final String ID_PK_COLUMN = "id";

    public Integer getGlperiod() {
        return (Integer)readProperty("glperiod");
    }

    public Integer getStartmonth() {
        return (Integer)readProperty("startmonth");
    }

}
