package accounting.ce.auto;

import java.sql.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import accounting.ce.Jcchangeorderstep;

/**
 * Class _Jcchangeorder was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Jcchangeorder extends CayenneDataObject {

    public static final String CONUM_PROPERTY = "conum";
    public static final String DATE_PROPERTY = "date";
    public static final String DES_PROPERTY = "des";
    public static final String JOBNUM_PROPERTY = "jobnum";
    public static final String NOTES_PROPERTY = "notes";
    public static final String ORDERNUM_PROPERTY = "ordernum";
    public static final String TYPE_PROPERTY = "type";
    public static final String CHANGEORDERSTEPS_PROPERTY = "changeordersteps";

    public static final String JOBNUM_PK_COLUMN = "jobnum";
    public static final String ORDERNUM_PK_COLUMN = "ordernum";

    public void setConum(String conum) {
        writeProperty("conum", conum);
    }
    public String getConum() {
        return (String)readProperty("conum");
    }

    public void setDate(Date date) {
        writeProperty("date", date);
    }
    public Date getDate() {
        return (Date)readProperty("date");
    }

    public void setDes(String des) {
        writeProperty("des", des);
    }
    public String getDes() {
        return (String)readProperty("des");
    }

    public void setJobnum(String jobnum) {
        writeProperty("jobnum", jobnum);
    }
    public String getJobnum() {
        return (String)readProperty("jobnum");
    }

    public void setNotes(String notes) {
        writeProperty("notes", notes);
    }
    public String getNotes() {
        return (String)readProperty("notes");
    }

    public void setOrdernum(String ordernum) {
        writeProperty("ordernum", ordernum);
    }
    public String getOrdernum() {
        return (String)readProperty("ordernum");
    }

    public void setType(Integer type) {
        writeProperty("type", type);
    }
    public Integer getType() {
        return (Integer)readProperty("type");
    }

    public void addToChangeordersteps(Jcchangeorderstep obj) {
        addToManyTarget("changeordersteps", obj, true);
    }
    public void removeFromChangeordersteps(Jcchangeorderstep obj) {
        removeToManyTarget("changeordersteps", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Jcchangeorderstep> getChangeordersteps() {
        return (List<Jcchangeorderstep>)readProperty("changeordersteps");
    }


}
