package accounting.ce.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Jcdetailsum was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Jcdetailsum extends CayenneDataObject {

    public static final String CATNUM_PROPERTY = "catnum";
    public static final String COST_PROPERTY = "cost";
    public static final String HOURS_PROPERTY = "hours";
    public static final String JOBNUM_PROPERTY = "jobnum";
    public static final String PHASENUM_PROPERTY = "phasenum";
    public static final String TYPE_PROPERTY = "type";

    public static final String CATNUM_PK_COLUMN = "catnum";
    public static final String JOBNUM_PK_COLUMN = "jobnum";
    public static final String PHASENUM_PK_COLUMN = "phasenum";
    public static final String TYPE_PK_COLUMN = "type";

    public void setCatnum(String catnum) {
        writeProperty("catnum", catnum);
    }
    public String getCatnum() {
        return (String)readProperty("catnum");
    }

    public void setCost(Double cost) {
        writeProperty("cost", cost);
    }
    public Double getCost() {
        return (Double)readProperty("cost");
    }

    public void setHours(Double hours) {
        writeProperty("hours", hours);
    }
    public Double getHours() {
        return (Double)readProperty("hours");
    }

    public void setJobnum(String jobnum) {
        writeProperty("jobnum", jobnum);
    }
    public String getJobnum() {
        return (String)readProperty("jobnum");
    }

    public void setPhasenum(String phasenum) {
        writeProperty("phasenum", phasenum);
    }
    public String getPhasenum() {
        return (String)readProperty("phasenum");
    }

    public void setType(Integer type) {
        writeProperty("type", type);
    }
    public Integer getType() {
        return (Integer)readProperty("type");
    }

}
