package accounting.ce.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import accounting.ce.Jccat;
import accounting.ce.Jcjob;
import accounting.ce.Jcphase;

/**
 * Class _Jcdetail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Jcdetail extends CayenneDataObject {

    public static final String CATNUM_PROPERTY = "catnum";
    public static final String COST_PROPERTY = "cost";
    public static final String DATE_PROPERTY = "date";
    public static final String DATEPOSTED_PROPERTY = "dateposted";
    public static final String DES1_PROPERTY = "des1";
    public static final String DES2_PROPERTY = "des2";
    public static final String GLPERIOD_PROPERTY = "glperiod";
    public static final String HOURS_PROPERTY = "hours";
    public static final String INVNUM_PROPERTY = "invnum";
    public static final String JCUNIQUE_PROPERTY = "jcunique";
    public static final String JOBNUM_PROPERTY = "jobnum";
    public static final String MINORTYPE_PROPERTY = "minortype";
    public static final String PHASENUM_PROPERTY = "phasenum";
    public static final String PONUM_PROPERTY = "ponum";
    public static final String SERIALNUM_PROPERTY = "serialnum";
    public static final String TYPE_PROPERTY = "type";
    public static final String WHO_PROPERTY = "who";
    public static final String CAT_PROPERTY = "cat";
    public static final String JOB_PROPERTY = "job";
    public static final String PHASE_PROPERTY = "phase";

    public static final String CATNUM_PK_COLUMN = "catnum";
    public static final String DATE_PK_COLUMN = "date";
    public static final String JOBNUM_PK_COLUMN = "jobnum";
    public static final String PHASENUM_PK_COLUMN = "phasenum";
    public static final String SERIALNUM_PK_COLUMN = "serialnum";

    public void setCatnum(String catnum) {
        writeProperty("catnum", catnum);
    }
    public String getCatnum() {
        return (String)readProperty("catnum");
    }

    public void setCost(Double cost) {
        writeProperty("cost", cost);
    }
    public Double getCost() {
        return (Double)readProperty("cost");
    }

    public void setDate(Date date) {
        writeProperty("date", date);
    }
    public Date getDate() {
        return (Date)readProperty("date");
    }

    public void setDateposted(Date dateposted) {
        writeProperty("dateposted", dateposted);
    }
    public Date getDateposted() {
        return (Date)readProperty("dateposted");
    }

    public void setDes1(String des1) {
        writeProperty("des1", des1);
    }
    public String getDes1() {
        return (String)readProperty("des1");
    }

    public void setDes2(String des2) {
        writeProperty("des2", des2);
    }
    public String getDes2() {
        return (String)readProperty("des2");
    }

    public void setGlperiod(Integer glperiod) {
        writeProperty("glperiod", glperiod);
    }
    public Integer getGlperiod() {
        return (Integer)readProperty("glperiod");
    }

    public void setHours(Double hours) {
        writeProperty("hours", hours);
    }
    public Double getHours() {
        return (Double)readProperty("hours");
    }

    public void setInvnum(String invnum) {
        writeProperty("invnum", invnum);
    }
    public String getInvnum() {
        return (String)readProperty("invnum");
    }

    public void setJcunique(Integer jcunique) {
        writeProperty("jcunique", jcunique);
    }
    public Integer getJcunique() {
        return (Integer)readProperty("jcunique");
    }

    public void setJobnum(String jobnum) {
        writeProperty("jobnum", jobnum);
    }
    public String getJobnum() {
        return (String)readProperty("jobnum");
    }

    public void setMinortype(Integer minortype) {
        writeProperty("minortype", minortype);
    }
    public Integer getMinortype() {
        return (Integer)readProperty("minortype");
    }

    public void setPhasenum(String phasenum) {
        writeProperty("phasenum", phasenum);
    }
    public String getPhasenum() {
        return (String)readProperty("phasenum");
    }

    public void setPonum(String ponum) {
        writeProperty("ponum", ponum);
    }
    public String getPonum() {
        return (String)readProperty("ponum");
    }

    public void setSerialnum(Integer serialnum) {
        writeProperty("serialnum", serialnum);
    }
    public Integer getSerialnum() {
        return (Integer)readProperty("serialnum");
    }

    public void setType(Integer type) {
        writeProperty("type", type);
    }
    public Integer getType() {
        return (Integer)readProperty("type");
    }

    public void setWho(String who) {
        writeProperty("who", who);
    }
    public String getWho() {
        return (String)readProperty("who");
    }

    public void setCat(Jccat cat) {
        setToOneTarget("cat", cat, true);
    }

    public Jccat getCat() {
        return (Jccat)readProperty("cat");
    }


    public void setJob(Jcjob job) {
        setToOneTarget("job", job, true);
    }

    public Jcjob getJob() {
        return (Jcjob)readProperty("job");
    }


    public void setPhase(Jcphase phase) {
        setToOneTarget("phase", phase, true);
    }

    public Jcphase getPhase() {
        return (Jcphase)readProperty("phase");
    }


}
