package accounting.ce.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import accounting.ce.Apvoucher;

/**
 * Class _Vendor was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Vendor extends CayenneDataObject {

    public static final String ADDRESS1_PROPERTY = "address1";
    public static final String ADDRESSCITY_PROPERTY = "addresscity";
    public static final String ADDRESSSTATE_PROPERTY = "addressstate";
    public static final String ADDRESSZIP_PROPERTY = "addresszip";
    public static final String COSTTYPE_PROPERTY = "costtype";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FAXNUM_PROPERTY = "faxnum";
    public static final String ID_PROPERTY = "id";
    public static final String MEMO_PROPERTY = "memo";
    public static final String NAME_PROPERTY = "name";
    public static final String NOTES1_PROPERTY = "notes1";
    public static final String NOTES2_PROPERTY = "notes2";
    public static final String PHONENUM_PROPERTY = "phonenum";
    public static final String VENNUM_PROPERTY = "vennum";
    public static final String WEB_PROPERTY = "web";
    public static final String VOUCHERS_PROPERTY = "vouchers";

    public static final String VENNUM_PK_COLUMN = "vennum";

    public String getAddress1() {
        return (String)readProperty("address1");
    }

    public String getAddresscity() {
        return (String)readProperty("addresscity");
    }

    public String getAddressstate() {
        return (String)readProperty("addressstate");
    }

    public String getAddresszip() {
        return (String)readProperty("addresszip");
    }

    public Integer getCosttype() {
        return (Integer)readProperty("costtype");
    }

    public String getEmail() {
        return (String)readProperty("email");
    }

    public String getFaxnum() {
        return (String)readProperty("faxnum");
    }

    public String getId() {
        return (String)readProperty("id");
    }

    public String getMemo() {
        return (String)readProperty("memo");
    }

    public String getName() {
        return (String)readProperty("name");
    }

    public String getNotes1() {
        return (String)readProperty("notes1");
    }

    public String getNotes2() {
        return (String)readProperty("notes2");
    }

    public String getPhonenum() {
        return (String)readProperty("phonenum");
    }

    public String getVennum() {
        return (String)readProperty("vennum");
    }

    public String getWeb() {
        return (String)readProperty("web");
    }

    public void addToVouchers(Apvoucher obj) {
        addToManyTarget("vouchers", obj, true);
    }
    public void removeFromVouchers(Apvoucher obj) {
        removeToManyTarget("vouchers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Apvoucher> getVouchers() {
        return (List<Apvoucher>)readProperty("vouchers");
    }


}
