package kf.auto;

import org.apache.cayenne.CayenneDataObject;

import kf.Document;
import kf.Project;
import kf.Projectfield;

/**
 * Class _Documentvalue was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Documentvalue extends CayenneDataObject {

    public static final String FIELD_ID_PROPERTY = "fieldID";
    public static final String FIELD_VALUE_PROPERTY = "fieldValue";
    public static final String DOCUMENT_PROPERTY = "document";
    public static final String PROJECT_PROPERTY = "project";
    public static final String PROJECTFIELD_PROPERTY = "projectfield";

    public static final String ID_PK_COLUMN = "ID";

    public void setFieldID(Long fieldID) {
        writeProperty("fieldID", fieldID);
    }
    public Long getFieldID() {
        return (Long)readProperty("fieldID");
    }

    public void setFieldValue(String fieldValue) {
        writeProperty("fieldValue", fieldValue);
    }
    public String getFieldValue() {
        return (String)readProperty("fieldValue");
    }

    public void setDocument(Document document) {
        setToOneTarget("document", document, true);
    }

    public Document getDocument() {
        return (Document)readProperty("document");
    }


    public void setProject(Project project) {
        setToOneTarget("project", project, true);
    }

    public Project getProject() {
        return (Project)readProperty("project");
    }


    public void setProjectfield(Projectfield projectfield) {
        setToOneTarget("projectfield", projectfield, true);
    }

    public Projectfield getProjectfield() {
        return (Projectfield)readProperty("projectfield");
    }


}
