package kf.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import kf.Document;
import kf.Project;
import kf.Workflowcomment;
import kf.Workflowstep;

/**
 * Class _Workflow was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Workflow extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String DATE_COMPLETED_PROPERTY = "dateCompleted";
    public static final String IS_FINISHED_PROPERTY = "isFinished";
    public static final String DOCUMENT_PROPERTY = "document";
    public static final String PROJECT_PROPERTY = "project";
    public static final String WORKFLOWCOMMENTS_PROPERTY = "workflowcomments";
    public static final String WORKFLOWSTEPS_PROPERTY = "workflowsteps";

    public static final String WORKFLOW_ID_PK_COLUMN = "WorkflowID";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDateCompleted(Date dateCompleted) {
        writeProperty("dateCompleted", dateCompleted);
    }
    public Date getDateCompleted() {
        return (Date)readProperty("dateCompleted");
    }

    public void setIsFinished(Boolean isFinished) {
        writeProperty("isFinished", isFinished);
    }
    public Boolean getIsFinished() {
        return (Boolean)readProperty("isFinished");
    }

    public void setDocument(Document document) {
        setToOneTarget("document", document, true);
    }

    public Document getDocument() {
        return (Document)readProperty("document");
    }


    public void setProject(Project project) {
        setToOneTarget("project", project, true);
    }

    public Project getProject() {
        return (Project)readProperty("project");
    }


    public void addToWorkflowcomments(Workflowcomment obj) {
        addToManyTarget("workflowcomments", obj, true);
    }
    public void removeFromWorkflowcomments(Workflowcomment obj) {
        removeToManyTarget("workflowcomments", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Workflowcomment> getWorkflowcomments() {
        return (List<Workflowcomment>)readProperty("workflowcomments");
    }


    public void addToWorkflowsteps(Workflowstep obj) {
        addToManyTarget("workflowsteps", obj, true);
    }
    public void removeFromWorkflowsteps(Workflowstep obj) {
        removeToManyTarget("workflowsteps", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Workflowstep> getWorkflowsteps() {
        return (List<Workflowstep>)readProperty("workflowsteps");
    }


}
