package kf.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import kf.Document;
import kf.Project;
import kf.User;
import kf.Workflow;
import kf.Workflowstep;

/**
 * Class _Workflowcomment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Workflowcomment extends CayenneDataObject {

    public static final String COMMENT_PROPERTY = "comment";
    public static final String DATE_PROPERTY = "date";
    public static final String DOCUMENT_PROPERTY = "document";
    public static final String PROJECT_PROPERTY = "project";
    public static final String USER_PROPERTY = "user";
    public static final String WORKFLOW_PROPERTY = "workflow";
    public static final String WORKFLOWSTEP_PROPERTY = "workflowstep";

    public static final String COMMENT_ID_PK_COLUMN = "CommentID";

    public void setComment(String comment) {
        writeProperty("comment", comment);
    }
    public String getComment() {
        return (String)readProperty("comment");
    }

    public void setDate(Date date) {
        writeProperty("date", date);
    }
    public Date getDate() {
        return (Date)readProperty("date");
    }

    public void setDocument(Document document) {
        setToOneTarget("document", document, true);
    }

    public Document getDocument() {
        return (Document)readProperty("document");
    }


    public void setProject(Project project) {
        setToOneTarget("project", project, true);
    }

    public Project getProject() {
        return (Project)readProperty("project");
    }


    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


    public void setWorkflow(Workflow workflow) {
        setToOneTarget("workflow", workflow, true);
    }

    public Workflow getWorkflow() {
        return (Workflow)readProperty("workflow");
    }


    public void setWorkflowstep(Workflowstep workflowstep) {
        setToOneTarget("workflowstep", workflowstep, true);
    }

    public Workflowstep getWorkflowstep() {
        return (Workflowstep)readProperty("workflowstep");
    }


}
