package kf.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import kf.Document;
import kf.Project;
import kf.User;
import kf.Workflow;
import kf.Workflowcomment;

/**
 * Class _Workflowstep was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Workflowstep extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String DATE_FINISHED_PROPERTY = "dateFinished";
    public static final String IS_STEP_FINISHED_PROPERTY = "isStepFinished";
    public static final String REASON_PROPERTY = "reason";
    public static final String DOCUMENT_PROPERTY = "document";
    public static final String FROM_USER_PROPERTY = "fromUser";
    public static final String PROJECTS_PROPERTY = "projects";
    public static final String TO_USER_PROPERTY = "toUser";
    public static final String WORKFLOW_PROPERTY = "workflow";
    public static final String WORKFLOWCOMMENT_PROPERTY = "workflowcomment";

    public static final String STEP_ID_PK_COLUMN = "StepID";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setDateFinished(Date dateFinished) {
        writeProperty("dateFinished", dateFinished);
    }
    public Date getDateFinished() {
        return (Date)readProperty("dateFinished");
    }

    public void setIsStepFinished(Boolean isStepFinished) {
        writeProperty("isStepFinished", isStepFinished);
    }
    public Boolean getIsStepFinished() {
        return (Boolean)readProperty("isStepFinished");
    }

    public void setReason(String reason) {
        writeProperty("reason", reason);
    }
    public String getReason() {
        return (String)readProperty("reason");
    }

    public void setDocument(Document document) {
        setToOneTarget("document", document, true);
    }

    public Document getDocument() {
        return (Document)readProperty("document");
    }


    public void setFromUser(User fromUser) {
        setToOneTarget("fromUser", fromUser, true);
    }

    public User getFromUser() {
        return (User)readProperty("fromUser");
    }


    public void setProjects(Project projects) {
        setToOneTarget("projects", projects, true);
    }

    public Project getProjects() {
        return (Project)readProperty("projects");
    }


    public void setToUser(User toUser) {
        setToOneTarget("toUser", toUser, true);
    }

    public User getToUser() {
        return (User)readProperty("toUser");
    }


    public void setWorkflow(Workflow workflow) {
        setToOneTarget("workflow", workflow, true);
    }

    public Workflow getWorkflow() {
        return (Workflow)readProperty("workflow");
    }


    public void addToWorkflowcomment(Workflowcomment obj) {
        addToManyTarget("workflowcomment", obj, true);
    }
    public void removeFromWorkflowcomment(Workflowcomment obj) {
        removeToManyTarget("workflowcomment", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Workflowcomment> getWorkflowcomment() {
        return (List<Workflowcomment>)readProperty("workflowcomment");
    }


}
