package accounting.ce.auto;

import org.apache.cayenne.CayenneDataObject;

import accounting.ce.Apvoucher;

/**
 * Class _Apcheck was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Apcheck extends CayenneDataObject {

    public static final String APAMT_PROPERTY = "apamt";
    public static final String CHECKNUM_PROPERTY = "checknum";
    public static final String NAME_PROPERTY = "name";
    public static final String VOUCHER_PROPERTY = "voucher";

    public static final String CHECKNUM_PK_COLUMN = "checknum";
    public static final String VOUCHERNUM_PK_COLUMN = "vouchernum";

    public Double getApamt() {
        return (Double)readProperty("apamt");
    }

    public Integer getChecknum() {
        return (Integer)readProperty("checknum");
    }

    public String getName() {
        return (String)readProperty("name");
    }


    public Apvoucher getVoucher() {
        return (Apvoucher)readProperty("voucher");
    }


}
