package accounting.ce.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import accounting.ce.Apvoucherdist;
import accounting.ce.Jcdetail;
import accounting.ce.Jcjob;
import accounting.ce.Jcphase;

/**
 * Class _Jccat was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Jccat extends CayenneDataObject {

    public static final String BUDGET0AMOUNT_PROPERTY = "budget0Amount";
    public static final String BUDGET0HOURS_PROPERTY = "budget0Hours";
    public static final String BUDGET10AMOUNT_PROPERTY = "budget10Amount";
    public static final String BUDGET10HOURS_PROPERTY = "budget10Hours";
    public static final String BUDGET11AMOUNT_PROPERTY = "budget11Amount";
    public static final String BUDGET11HOURS_PROPERTY = "budget11Hours";
    public static final String BUDGET12AMOUNT_PROPERTY = "budget12Amount";
    public static final String BUDGET12HOURS_PROPERTY = "budget12Hours";
    public static final String BUDGET13AMOUNT_PROPERTY = "budget13Amount";
    public static final String BUDGET13HOURS_PROPERTY = "budget13Hours";
    public static final String BUDGET14AMOUNT_PROPERTY = "budget14Amount";
    public static final String BUDGET14HOURS_PROPERTY = "budget14Hours";
    public static final String BUDGET15AMOUNT_PROPERTY = "budget15Amount";
    public static final String BUDGET15HOURS_PROPERTY = "budget15Hours";
    public static final String BUDGET16AMOUNT_PROPERTY = "budget16Amount";
    public static final String BUDGET16HOURS_PROPERTY = "budget16Hours";
    public static final String BUDGET1AMOUNT_PROPERTY = "budget1Amount";
    public static final String BUDGET1HOURS_PROPERTY = "budget1Hours";
    public static final String BUDGET2AMOUNT_PROPERTY = "budget2Amount";
    public static final String BUDGET2HOURS_PROPERTY = "budget2Hours";
    public static final String BUDGET3AMOUNT_PROPERTY = "budget3Amount";
    public static final String BUDGET3HOURS_PROPERTY = "budget3Hours";
    public static final String BUDGET4AMOUNT_PROPERTY = "budget4Amount";
    public static final String BUDGET4HOURS_PROPERTY = "budget4Hours";
    public static final String BUDGET5AMOUNT_PROPERTY = "budget5Amount";
    public static final String BUDGET5HOURS_PROPERTY = "budget5Hours";
    public static final String BUDGET6AMOUNT_PROPERTY = "budget6Amount";
    public static final String BUDGET6HOURS_PROPERTY = "budget6Hours";
    public static final String BUDGET7AMOUNT_PROPERTY = "budget7Amount";
    public static final String BUDGET7HOURS_PROPERTY = "budget7Hours";
    public static final String BUDGET8AMOUNT_PROPERTY = "budget8Amount";
    public static final String BUDGET8HOURS_PROPERTY = "budget8Hours";
    public static final String BUDGET9AMOUNT_PROPERTY = "budget9Amount";
    public static final String BUDGET9HOURS_PROPERTY = "budget9Hours";
    public static final String CATNUM_PROPERTY = "catnum";
    public static final String JOBNUM_PROPERTY = "jobnum";
    public static final String NAME_PROPERTY = "name";
    public static final String PHASENUM_PROPERTY = "phasenum";
    public static final String SEQUENCE_PROPERTY = "sequence";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String JOB_PROPERTY = "job";
    public static final String PHASE_PROPERTY = "phase";
    public static final String VOUCHERDIST_PROPERTY = "voucherdist";

    public static final String CATNUM_PK_COLUMN = "catnum";
    public static final String JOBNUM_PK_COLUMN = "jobnum";
    public static final String PHASENUM_PK_COLUMN = "phasenum";

    public void setBudget0Amount(Double budget0Amount) {
        writeProperty("budget0Amount", budget0Amount);
    }
    public Double getBudget0Amount() {
        return (Double)readProperty("budget0Amount");
    }

    public void setBudget0Hours(Double budget0Hours) {
        writeProperty("budget0Hours", budget0Hours);
    }
    public Double getBudget0Hours() {
        return (Double)readProperty("budget0Hours");
    }

    public void setBudget10Amount(Double budget10Amount) {
        writeProperty("budget10Amount", budget10Amount);
    }
    public Double getBudget10Amount() {
        return (Double)readProperty("budget10Amount");
    }

    public void setBudget10Hours(Double budget10Hours) {
        writeProperty("budget10Hours", budget10Hours);
    }
    public Double getBudget10Hours() {
        return (Double)readProperty("budget10Hours");
    }

    public void setBudget11Amount(Double budget11Amount) {
        writeProperty("budget11Amount", budget11Amount);
    }
    public Double getBudget11Amount() {
        return (Double)readProperty("budget11Amount");
    }

    public void setBudget11Hours(Double budget11Hours) {
        writeProperty("budget11Hours", budget11Hours);
    }
    public Double getBudget11Hours() {
        return (Double)readProperty("budget11Hours");
    }

    public void setBudget12Amount(Double budget12Amount) {
        writeProperty("budget12Amount", budget12Amount);
    }
    public Double getBudget12Amount() {
        return (Double)readProperty("budget12Amount");
    }

    public void setBudget12Hours(Double budget12Hours) {
        writeProperty("budget12Hours", budget12Hours);
    }
    public Double getBudget12Hours() {
        return (Double)readProperty("budget12Hours");
    }

    public void setBudget13Amount(Double budget13Amount) {
        writeProperty("budget13Amount", budget13Amount);
    }
    public Double getBudget13Amount() {
        return (Double)readProperty("budget13Amount");
    }

    public void setBudget13Hours(Double budget13Hours) {
        writeProperty("budget13Hours", budget13Hours);
    }
    public Double getBudget13Hours() {
        return (Double)readProperty("budget13Hours");
    }

    public void setBudget14Amount(Double budget14Amount) {
        writeProperty("budget14Amount", budget14Amount);
    }
    public Double getBudget14Amount() {
        return (Double)readProperty("budget14Amount");
    }

    public void setBudget14Hours(Double budget14Hours) {
        writeProperty("budget14Hours", budget14Hours);
    }
    public Double getBudget14Hours() {
        return (Double)readProperty("budget14Hours");
    }

    public void setBudget15Amount(Double budget15Amount) {
        writeProperty("budget15Amount", budget15Amount);
    }
    public Double getBudget15Amount() {
        return (Double)readProperty("budget15Amount");
    }

    public void setBudget15Hours(Double budget15Hours) {
        writeProperty("budget15Hours", budget15Hours);
    }
    public Double getBudget15Hours() {
        return (Double)readProperty("budget15Hours");
    }

    public void setBudget16Amount(Double budget16Amount) {
        writeProperty("budget16Amount", budget16Amount);
    }
    public Double getBudget16Amount() {
        return (Double)readProperty("budget16Amount");
    }

    public void setBudget16Hours(Double budget16Hours) {
        writeProperty("budget16Hours", budget16Hours);
    }
    public Double getBudget16Hours() {
        return (Double)readProperty("budget16Hours");
    }

    public void setBudget1Amount(Double budget1Amount) {
        writeProperty("budget1Amount", budget1Amount);
    }
    public Double getBudget1Amount() {
        return (Double)readProperty("budget1Amount");
    }

    public void setBudget1Hours(Double budget1Hours) {
        writeProperty("budget1Hours", budget1Hours);
    }
    public Double getBudget1Hours() {
        return (Double)readProperty("budget1Hours");
    }

    public void setBudget2Amount(Double budget2Amount) {
        writeProperty("budget2Amount", budget2Amount);
    }
    public Double getBudget2Amount() {
        return (Double)readProperty("budget2Amount");
    }

    public void setBudget2Hours(Double budget2Hours) {
        writeProperty("budget2Hours", budget2Hours);
    }
    public Double getBudget2Hours() {
        return (Double)readProperty("budget2Hours");
    }

    public void setBudget3Amount(Double budget3Amount) {
        writeProperty("budget3Amount", budget3Amount);
    }
    public Double getBudget3Amount() {
        return (Double)readProperty("budget3Amount");
    }

    public void setBudget3Hours(Double budget3Hours) {
        writeProperty("budget3Hours", budget3Hours);
    }
    public Double getBudget3Hours() {
        return (Double)readProperty("budget3Hours");
    }

    public void setBudget4Amount(Double budget4Amount) {
        writeProperty("budget4Amount", budget4Amount);
    }
    public Double getBudget4Amount() {
        return (Double)readProperty("budget4Amount");
    }

    public void setBudget4Hours(Double budget4Hours) {
        writeProperty("budget4Hours", budget4Hours);
    }
    public Double getBudget4Hours() {
        return (Double)readProperty("budget4Hours");
    }

    public void setBudget5Amount(Double budget5Amount) {
        writeProperty("budget5Amount", budget5Amount);
    }
    public Double getBudget5Amount() {
        return (Double)readProperty("budget5Amount");
    }

    public void setBudget5Hours(Double budget5Hours) {
        writeProperty("budget5Hours", budget5Hours);
    }
    public Double getBudget5Hours() {
        return (Double)readProperty("budget5Hours");
    }

    public void setBudget6Amount(Double budget6Amount) {
        writeProperty("budget6Amount", budget6Amount);
    }
    public Double getBudget6Amount() {
        return (Double)readProperty("budget6Amount");
    }

    public void setBudget6Hours(Double budget6Hours) {
        writeProperty("budget6Hours", budget6Hours);
    }
    public Double getBudget6Hours() {
        return (Double)readProperty("budget6Hours");
    }

    public void setBudget7Amount(Double budget7Amount) {
        writeProperty("budget7Amount", budget7Amount);
    }
    public Double getBudget7Amount() {
        return (Double)readProperty("budget7Amount");
    }

    public void setBudget7Hours(Double budget7Hours) {
        writeProperty("budget7Hours", budget7Hours);
    }
    public Double getBudget7Hours() {
        return (Double)readProperty("budget7Hours");
    }

    public void setBudget8Amount(Double budget8Amount) {
        writeProperty("budget8Amount", budget8Amount);
    }
    public Double getBudget8Amount() {
        return (Double)readProperty("budget8Amount");
    }

    public void setBudget8Hours(Double budget8Hours) {
        writeProperty("budget8Hours", budget8Hours);
    }
    public Double getBudget8Hours() {
        return (Double)readProperty("budget8Hours");
    }

    public void setBudget9Amount(Double budget9Amount) {
        writeProperty("budget9Amount", budget9Amount);
    }
    public Double getBudget9Amount() {
        return (Double)readProperty("budget9Amount");
    }

    public void setBudget9Hours(Double budget9Hours) {
        writeProperty("budget9Hours", budget9Hours);
    }
    public Double getBudget9Hours() {
        return (Double)readProperty("budget9Hours");
    }

    public void setCatnum(String catnum) {
        writeProperty("catnum", catnum);
    }
    public String getCatnum() {
        return (String)readProperty("catnum");
    }

    public void setJobnum(String jobnum) {
        writeProperty("jobnum", jobnum);
    }
    public String getJobnum() {
        return (String)readProperty("jobnum");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPhasenum(String phasenum) {
        writeProperty("phasenum", phasenum);
    }
    public String getPhasenum() {
        return (String)readProperty("phasenum");
    }

    public void setSequence(Integer sequence) {
        writeProperty("sequence", sequence);
    }
    public Integer getSequence() {
        return (Integer)readProperty("sequence");
    }

    public void addToDetail(Jcdetail obj) {
        addToManyTarget("detail", obj, true);
    }
    public void removeFromDetail(Jcdetail obj) {
        removeToManyTarget("detail", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Jcdetail> getDetail() {
        return (List<Jcdetail>)readProperty("detail");
    }


    public void setJob(Jcjob job) {
        setToOneTarget("job", job, true);
    }

    public Jcjob getJob() {
        return (Jcjob)readProperty("job");
    }


    public void setPhase(Jcphase phase) {
        setToOneTarget("phase", phase, true);
    }

    public Jcphase getPhase() {
        return (Jcphase)readProperty("phase");
    }


    public void addToVoucherdist(Apvoucherdist obj) {
        addToManyTarget("voucherdist", obj, true);
    }
    public void removeFromVoucherdist(Apvoucherdist obj) {
        removeToManyTarget("voucherdist", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Apvoucherdist> getVoucherdist() {
        return (List<Apvoucherdist>)readProperty("voucherdist");
    }


}
