package accounting.ce.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import accounting.ce.Apvoucherdist;
import accounting.ce.Jccat;
import accounting.ce.Jcdetail;
import accounting.ce.Jcphase;

/**
 * Class _Jcjob was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Jcjob extends CayenneDataObject {

    public static final String JOBNUM_PROPERTY = "jobnum";
    public static final String OVERHEADPCNT1_PROPERTY = "overheadpcnt1";
    public static final String OVERHEADPCNT10_PROPERTY = "overheadpcnt10";
    public static final String OVERHEADPCNT11_PROPERTY = "overheadpcnt11";
    public static final String OVERHEADPCNT12_PROPERTY = "overheadpcnt12";
    public static final String OVERHEADPCNT13_PROPERTY = "overheadpcnt13";
    public static final String OVERHEADPCNT14_PROPERTY = "overheadpcnt14";
    public static final String OVERHEADPCNT15_PROPERTY = "overheadpcnt15";
    public static final String OVERHEADPCNT16_PROPERTY = "overheadpcnt16";
    public static final String OVERHEADPCNT2_PROPERTY = "overheadpcnt2";
    public static final String OVERHEADPCNT3_PROPERTY = "overheadpcnt3";
    public static final String OVERHEADPCNT4_PROPERTY = "overheadpcnt4";
    public static final String OVERHEADPCNT5_PROPERTY = "overheadpcnt5";
    public static final String OVERHEADPCNT6_PROPERTY = "overheadpcnt6";
    public static final String OVERHEADPCNT7_PROPERTY = "overheadpcnt7";
    public static final String OVERHEADPCNT8_PROPERTY = "overheadpcnt8";
    public static final String OVERHEADPCNT9_PROPERTY = "overheadpcnt9";
    public static final String CATS_PROPERTY = "cats";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String PHASES_PROPERTY = "phases";
    public static final String VOUCHERDIST_PROPERTY = "voucherdist";

    public static final String JOBNUM_PK_COLUMN = "jobnum";

    public String getJobnum() {
        return (String)readProperty("jobnum");
    }

    public Float getOverheadpcnt1() {
        return (Float)readProperty("overheadpcnt1");
    }

    public Float getOverheadpcnt10() {
        return (Float)readProperty("overheadpcnt10");
    }

    public Float getOverheadpcnt11() {
        return (Float)readProperty("overheadpcnt11");
    }

    public Float getOverheadpcnt12() {
        return (Float)readProperty("overheadpcnt12");
    }

    public Float getOverheadpcnt13() {
        return (Float)readProperty("overheadpcnt13");
    }

    public Float getOverheadpcnt14() {
        return (Float)readProperty("overheadpcnt14");
    }

    public Float getOverheadpcnt15() {
        return (Float)readProperty("overheadpcnt15");
    }

    public Float getOverheadpcnt16() {
        return (Float)readProperty("overheadpcnt16");
    }

    public Float getOverheadpcnt2() {
        return (Float)readProperty("overheadpcnt2");
    }

    public Float getOverheadpcnt3() {
        return (Float)readProperty("overheadpcnt3");
    }

    public Float getOverheadpcnt4() {
        return (Float)readProperty("overheadpcnt4");
    }

    public Float getOverheadpcnt5() {
        return (Float)readProperty("overheadpcnt5");
    }

    public Float getOverheadpcnt6() {
        return (Float)readProperty("overheadpcnt6");
    }

    public Float getOverheadpcnt7() {
        return (Float)readProperty("overheadpcnt7");
    }

    public Float getOverheadpcnt8() {
        return (Float)readProperty("overheadpcnt8");
    }

    public Float getOverheadpcnt9() {
        return (Float)readProperty("overheadpcnt9");
    }

    public void addToCats(Jccat obj) {
        addToManyTarget("cats", obj, true);
    }
    public void removeFromCats(Jccat obj) {
        removeToManyTarget("cats", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Jccat> getCats() {
        return (List<Jccat>)readProperty("cats");
    }


    public void addToDetail(Jcdetail obj) {
        addToManyTarget("detail", obj, true);
    }
    public void removeFromDetail(Jcdetail obj) {
        removeToManyTarget("detail", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Jcdetail> getDetail() {
        return (List<Jcdetail>)readProperty("detail");
    }


    public void addToPhases(Jcphase obj) {
        addToManyTarget("phases", obj, true);
    }
    public void removeFromPhases(Jcphase obj) {
        removeToManyTarget("phases", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Jcphase> getPhases() {
        return (List<Jcphase>)readProperty("phases");
    }


    public void addToVoucherdist(Apvoucherdist obj) {
        addToManyTarget("voucherdist", obj, true);
    }
    public void removeFromVoucherdist(Apvoucherdist obj) {
        removeToManyTarget("voucherdist", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Apvoucherdist> getVoucherdist() {
        return (List<Apvoucherdist>)readProperty("voucherdist");
    }


}
