alter table transmittal drop column username;
alter table transmittal modify column created date;
alter table transmittal drop column created_by;
alter table transmittal drop column created_username;
alter table transmittal drop column updated;
alter table transmittal drop column updated_by;
alter table transmittal drop column updated_username;
alter table transmittal drop column old_id;
alter table change_requests drop column signed_by;
alter table change_requests drop column signed_username;
alter table change_requests drop column created;
alter table change_requests drop column created_by;
alter table change_requests drop column created_username;
alter table change_requests drop column updated;
alter table change_requests drop column updated_by;
alter table change_requests drop column updated_username;
alter table change_request_detail drop column created;
alter table change_request_detail drop column created_by;
alter table change_request_detail drop column created_username;
alter table change_request_detail drop column updated;
alter table change_request_detail drop column updated_by;
alter table change_request_detail drop column updated_username;
alter table company_comments drop column username;
alter table company_comments drop column updated;
alter table company_comments drop column fullname;
alter table letters drop column username;
alter table letters drop column user;
alter table rfi drop column username;
alter table rfi drop column user;
alter table submittals drop column username;
alter table submittals drop column user;
alter table job_team drop column username;
alter table job_permissions drop column username;
alter table pay_requests drop column int_modified;
alter table pay_requests drop column ext_modified;
alter table pay_requests drop column int_mod_by;
alter table pay_requests drop column ext_mod_by;
alter table fax_log drop column username;
alter table error_log drop column username;
alter table session_log drop column username;
alter table user_jobs drop column username;
alter table session_log drop index (user_id_2);
alter table session_log drop index (user_id_3);
alter table suspense_cache drop index (voucher_id_2);
alter table suspense_cache drop index (voucher_id_3);
alter table suspense_cache drop index (voucher_id_4);
alter table suspense_cache drop index (voucher_id_5);
alter table suspense_cache drop index (voucher_id_6);
insert ignore into settings (id, name, val) values ("site", "asterisk_host", "pbx.e-p.com");
insert ignore into settings (id, name, val) values ("site", "asterisk_port", "5038");
insert ignore into settings (id, name, val) values ("site", "asterisk_user", "admin");
insert ignore into settings (id, name, val) values ("site", "asterisk_pass", "amp111");
insert ignore into settings (id, name, val) values ("site", "asterisk_prefix", "6");
insert ignore into settings (id, name, val) values ("site", "asterisk_context", "from-internal");
alter table change_request_detail add created date default null;
update change_request_detail, log set created = stamp where crd_id = id and type = "CD";
update change_request_detail set created = null where created = "1969-12-31";
