package kf.config.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Company was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Company extends CayenneDataObject {

    public static final String COMPANY_ID_PROPERTY = "companyId";
    public static final String COMPANY_NAME_PROPERTY = "companyName";
    public static final String D_BNAME_PROPERTY = "dBName";
    public static final String D_BPASSWORD_PROPERTY = "dBPassword";
    public static final String D_BSERVER_PROPERTY = "dBServer";
    public static final String D_BUSERNAME_PROPERTY = "dBUsername";
    public static final String KEY_NAME_PROPERTY = "keyName";
    public static final String LICENSES_PROPERTY = "licenses";
    public static final String REGISTRATION_KEY_PROPERTY = "registrationKey";

    public static final String COMPANY_ID_PK_COLUMN = "CompanyID";

    public Long getCompanyId() {
        return (Long)readProperty("companyId");
    }

    public String getCompanyName() {
        return (String)readProperty("companyName");
    }

    public String getDBName() {
        return (String)readProperty("dBName");
    }

    public String getDBPassword() {
        return (String)readProperty("dBPassword");
    }

    public String getDBServer() {
        return (String)readProperty("dBServer");
    }

    public String getDBUsername() {
        return (String)readProperty("dBUsername");
    }

    public String getKeyName() {
        return (String)readProperty("keyName");
    }

    public Integer getLicenses() {
        return (Integer)readProperty("licenses");
    }

    public String getRegistrationKey() {
        return (String)readProperty("registrationKey");
    }

}
