package kf.config.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Customerconfig was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Customerconfig extends CayenneDataObject {

    public static final String CUSTOMER_ID_PROPERTY = "customerID";
    public static final String CUSTOMER_NAME_PROPERTY = "customerName";
    public static final String DEFAULT_ACCESS_METHOD_PROPERTY = "defaultAccessMethod";
    public static final String ID_PROPERTY = "id";
    public static final String NETWORK_CACHE_PROPERTY = "networkCache";
    public static final String PROJECT_ROOT_PROPERTY = "projectRoot";
    public static final String REGISTRATION_KEY_PROPERTY = "registrationKey";
    public static final String S_MTPPASSWORD_PROPERTY = "sMTPPassword";
    public static final String S_MTPSERVER_PROPERTY = "sMTPServer";
    public static final String S_MTPUSERNAME_PROPERTY = "sMTPUsername";
    public static final String SERVER_IP_PROPERTY = "serverIP";
    public static final String WEB_CACHE_FOLDER_PROPERTY = "webCacheFolder";
    public static final String WEB_CACHE_METHOD_PROPERTY = "webCacheMethod";
    public static final String WEB_CACHE_PASSWORD_PROPERTY = "webCachePassword";
    public static final String WEB_CACHE_PATH_PROPERTY = "webCachePath";
    public static final String WEB_CACHE_SERVER_PROPERTY = "webCacheServer";
    public static final String WEB_CACHE_USERNAME_PROPERTY = "webCacheUsername";

    public static final String ID_PK_COLUMN = "id";

    public Integer getCustomerID() {
        return (Integer)readProperty("customerID");
    }

    public String getCustomerName() {
        return (String)readProperty("customerName");
    }

    public String getDefaultAccessMethod() {
        return (String)readProperty("defaultAccessMethod");
    }

    public Long getId() {
        return (Long)readProperty("id");
    }

    public String getNetworkCache() {
        return (String)readProperty("networkCache");
    }

    public String getProjectRoot() {
        return (String)readProperty("projectRoot");
    }

    public String getRegistrationKey() {
        return (String)readProperty("registrationKey");
    }

    public String getSMTPPassword() {
        return (String)readProperty("sMTPPassword");
    }

    public String getSMTPServer() {
        return (String)readProperty("sMTPServer");
    }

    public String getSMTPUsername() {
        return (String)readProperty("sMTPUsername");
    }

    public String getServerIP() {
        return (String)readProperty("serverIP");
    }

    public String getWebCacheFolder() {
        return (String)readProperty("webCacheFolder");
    }

    public String getWebCacheMethod() {
        return (String)readProperty("webCacheMethod");
    }

    public String getWebCachePassword() {
        return (String)readProperty("webCachePassword");
    }

    public String getWebCachePath() {
        return (String)readProperty("webCachePath");
    }

    public String getWebCacheServer() {
        return (String)readProperty("webCacheServer");
    }

    public String getWebCacheUsername() {
        return (String)readProperty("webCacheUsername");
    }

}
