package kf.auto;

import org.apache.cayenne.CayenneDataObject;

import kf.Document;
import kf.Project;
import kf.User;

/**
 * Class _Page was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Page extends CayenneDataObject {

    public static final String BATCH_ID_PROPERTY = "batchID";
    public static final String DATE_CREATED_PROPERTY = "dateCreated";
    public static final String EXTENSION_PROPERTY = "extension";
    public static final String PAGE_ID_PROPERTY = "pageID";
    public static final String PAGE_ORDER_PROPERTY = "pageOrder";
    public static final String DOCUMENT_PROPERTY = "document";
    public static final String PROJECT_PROPERTY = "project";
    public static final String USERS_PROPERTY = "users";

    public static final String PAGE_ID_PK_COLUMN = "PageID";

    public Integer getBatchID() {
        return (Integer)readProperty("batchID");
    }

    public Integer getDateCreated() {
        return (Integer)readProperty("dateCreated");
    }

    public String getExtension() {
        return (String)readProperty("extension");
    }

    public Long getPageID() {
        return (Long)readProperty("pageID");
    }

    public Integer getPageOrder() {
        return (Integer)readProperty("pageOrder");
    }


    public Document getDocument() {
        return (Document)readProperty("document");
    }



    public Project getProject() {
        return (Project)readProperty("project");
    }



    public User getUsers() {
        return (User)readProperty("users");
    }


}
