package kf.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import kf.Page;
import kf.Workflowcomment;
import kf.Workflowstep;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String IMG_URL_PROPERTY = "imgUrl";
    public static final String LAST_ACTIVITY_DATE_PROPERTY = "lastActivityDate";
    public static final String LAST_IP_PROPERTY = "lastIP";
    public static final String LAST_LOGIN_DATE_PROPERTY = "lastLoginDate";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String LOGGED_IN_PROPERTY = "loggedIn";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String PHONE_PROPERTY = "phone";
    public static final String START_PAGE_PROPERTY = "startPage";
    public static final String STATUS_PROPERTY = "status";
    public static final String TIME_ZONE_PROPERTY = "timeZone";
    public static final String USER_ID_PROPERTY = "userID";
    public static final String USERNAME_PROPERTY = "username";
    public static final String PAGES_PROPERTY = "pages";
    public static final String RECEIVED_WORKFLOWSTEPS_PROPERTY = "receivedWorkflowsteps";
    public static final String SENT_WORKFLOWSTEPS_PROPERTY = "sentWorkflowsteps";
    public static final String WORKFLOWCOMMENTS_PROPERTY = "workflowcomments";

    public static final String USER_ID_PK_COLUMN = "UserID";

    public String getEmail() {
        return (String)readProperty("email");
    }

    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public String getImgUrl() {
        return (String)readProperty("imgUrl");
    }

    public Date getLastActivityDate() {
        return (Date)readProperty("lastActivityDate");
    }

    public String getLastIP() {
        return (String)readProperty("lastIP");
    }

    public Date getLastLoginDate() {
        return (Date)readProperty("lastLoginDate");
    }

    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public Boolean getLoggedIn() {
        return (Boolean)readProperty("loggedIn");
    }

    public String getPassword() {
        return (String)readProperty("password");
    }

    public String getPhone() {
        return (String)readProperty("phone");
    }

    public String getStartPage() {
        return (String)readProperty("startPage");
    }

    public String getStatus() {
        return (String)readProperty("status");
    }

    public Integer getTimeZone() {
        return (Integer)readProperty("timeZone");
    }

    public Long getUserID() {
        return (Long)readProperty("userID");
    }

    public String getUsername() {
        return (String)readProperty("username");
    }

    public void addToPages(Page obj) {
        addToManyTarget("pages", obj, true);
    }
    public void removeFromPages(Page obj) {
        removeToManyTarget("pages", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Page> getPages() {
        return (List<Page>)readProperty("pages");
    }


    public void addToReceivedWorkflowsteps(Workflowstep obj) {
        addToManyTarget("receivedWorkflowsteps", obj, true);
    }
    public void removeFromReceivedWorkflowsteps(Workflowstep obj) {
        removeToManyTarget("receivedWorkflowsteps", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Workflowstep> getReceivedWorkflowsteps() {
        return (List<Workflowstep>)readProperty("receivedWorkflowsteps");
    }


    public void addToSentWorkflowsteps(Workflowstep obj) {
        addToManyTarget("sentWorkflowsteps", obj, true);
    }
    public void removeFromSentWorkflowsteps(Workflowstep obj) {
        removeToManyTarget("sentWorkflowsteps", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Workflowstep> getSentWorkflowsteps() {
        return (List<Workflowstep>)readProperty("sentWorkflowsteps");
    }


    public void addToWorkflowcomments(Workflowcomment obj) {
        addToManyTarget("workflowcomments", obj, true);
    }
    public void removeFromWorkflowcomments(Workflowcomment obj) {
        removeToManyTarget("workflowcomments", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Workflowcomment> getWorkflowcomments() {
        return (List<Workflowcomment>)readProperty("workflowcomments");
    }


}
